version: '3.6'
services:
  davinci:
    environment:
      - SERVER_ADDRESS=0.0.0.0
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/davinci0.3?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=abc123123
      - SPRING_DATASOURCE_TEST_ON_BORROW=true
      - SPRING_DATASOURCE_TIME_BETWEEN_EVICTION_RUNS_MILLIS=6000
      - SPRING_MAIL_HOST=smtp.163.com
      - SPRING_MAIL_PORT=465
      - SPRING_MAIL_USERNAME=02131261@163.com
      - SPRING_MAIL_PASSWORD=vcvcvvc
      - SPRING_MAIL_NICKNAME=02131261
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_ENABLE=true
      - SCREENSHOT_PHANTOMJS_PATH=/opt/phantomjs-2.1.1/phantomjs
    image: "edp963/davinci:v0.3.0-beta.8"
    ports:
      - 8080:8080
    command: ["./bin/docker-entrypoint.sh", "mysql:3306", "--", "start-server.sh"]
    restart: always
    volumes:
      - davinci_logs:/opt/davinci/logs
      - davinci_userfiles:/opt/davinci/userfiles
      - davinci_initdb:/initdb
  mysql:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=abc123123
      - MYSQL_DATABASE=davinci0.3
    ports:
      - 3306:3306    
    volumes:
      - mysql_data:/var/lib/mysql
      - davinci_initdb:/docker-entrypoint-initdb.d:ro

volumes:
  davinci_userfiles:
  davinci_logs:
  davinci_initdb:
  mysql_data:

    
